### PR TITLE
Footer section

### PR DESCRIPTION
**Pull request by Abdullloh**
I have added footer section to our master branch

### CODE REVIEW

**Comment by Abdullloh** [comment]
I have added footer section to our master branch

**Review by Alisher778 — CHANGES_REQUESTED** [review]
Uzur sizda style va index.html bilan conflict bor. To'g'irlab qaytadan pull request qiling.

**Comment by Abdullloh** [comment]
Tögirlab dganda nmani nazarda tutepsiz.

**Comment by Abdullloh** [comment]
Bir marta push qigandan kyn qayta push qib bumedimi yani ketingi safar pull
qiliw kiremi

**Comment by Abdullloh** [comment]
Ustoz stajirovka ga bita company topudim. Borsam buladimi yoki hali vaqtlimi

**Pull request merged**
